baseURL = "https://chz-cc.github.io/"
languageCode = 'en-us'
title = "起风了"
theme = "contrast"
sectionPagesMenu = 'main'

summaryLength = 2
toc = false
autoCollapseToc = true

paginate = 3

[params]
  minimal = false
  excerpts = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "关于我"
    url = "/about"
    weight =  50
  [[menu.main]]
    identifier = "notes"
    name = "笔记"
    url = "/notes/til"
    weight = 30
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/articles"
    weight = 20

[permalinks]
  [permalinks.page]
    posts = '/articles/:slug/'
    notes = '/notes/:slug/'
  [permalinks.section]
    posts = '/articles/'
    notes = '/notes/'

[taxonomies]
  category = 'categories'
  tag = 'tags'

[markup]
  [markup.tableOfContents]
    endLevel = 6
    ordered = false
    startLevel = 2