baseURL = "https://chz-cc.github.io/"
languageCode = 'en-us'
title = "起风了"
theme = "contrast"

[params]
  minimal = false
  excerpts = false

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 10

[permalinks]
  [permalinks.page]
    posts = '/articles/:slug/'
    notes = '/notes/:slug/'
  [permalinks.section]
    posts = '/articles/'
    notes = '/notes/'